name: Security Code Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        id: semgrep
        continue-on-error: true
        run: |
          semgrep scan \
            --config p/default \
            --severity ERROR \
            --json \
            --output semgrep.json
